### ISSUE TITLE
Use the node version in .nvmrc for GH Actions in all repositories

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/.github#14]
This task implies 
- creating the `.nvmrc` file if it doesn't exist, containing the node version to use
- add two steps in the github workflows:
```
      - name: Read node version from .nvmrc
        id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvmrc.outputs.NODE_VERSION }}"
```

for each one of the following repositories

* [x] circles-core https://github.com/CirclesUBI/circles-core/pull/67
* [x] circles-api https://github.com/CirclesUBI/circles-api/pull/50
* [x] circles-myxogastria https://github.com/CirclesUBI/circles-myxogastria/pull/163
* [x] circles-transfer https://github.com/CirclesUBI/circles-transfer/pull/5
* [x] circles-contracts https://github.com/CirclesUBI/circles-contracts/pull/121
